"""empty message

Revision ID: 0447cc1d2d22
Revises: f29f3072b4c7
Create Date: 2022-06-15 16:10:25.724925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0447cc1d2d22'
down_revision = 'f29f3072b4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birthplan_form', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('birthplan_form', 'full_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('birthplan_form', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('birthplan_form', 'phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('birthplan_form', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_foreign_key(None, 'birthplan_form', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'birthplan_form', type_='foreignkey')
    op.alter_column('birthplan_form', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('birthplan_form', 'phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('birthplan_form', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('birthplan_form', 'full_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('birthplan_form', 'user_id')
    # ### end Alembic commands ###
