"""empty message

Revision ID: 0f58bbdb06cb
Revises: 27c1cec0a11f
Create Date: 2022-05-19 19:18:57.156797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f58bbdb06cb'
down_revision = '27c1cec0a11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('rol', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user__data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('pregnancy_weeks', sa.Integer(), nullable=True),
    sa.Column('aproximate_birth_date', sa.Date(), nullable=True),
    sa.Column('children_number', sa.Integer(), nullable=True),
    sa.Column('caesarean_sections_number', sa.Integer(), nullable=True),
    sa.Column('companion', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('birth_place', sa.String(length=120), nullable=True),
    sa.Column('current_hospital', sa.String(length=250), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('datos__usuaria')
    op.drop_table('usuarias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarias',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('usuarias_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('contraseña', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('rol', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usuarias_pkey'),
    sa.UniqueConstraint('email', name='usuarias_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('datos__usuaria',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuaria_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('semanas_embarazo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_aproximada_parto', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('numero_hijos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numero_cesareas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acompanante', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('ciudad', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('lugar_parto', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('hospital_actual', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuaria_id'], ['usuarias.id'], name='datos__usuaria_usuaria_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='datos__usuaria_pkey')
    )
    op.drop_table('user__data')
    op.drop_table('users')
    # ### end Alembic commands ###
