"""empty message

Revision ID: 17f6912227d0
Revises: f4c0cb7fd64d
Create Date: 2022-05-26 17:32:18.429700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f6912227d0'
down_revision = 'f4c0cb7fd64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_rols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['user_rol.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('service', sa.Column('qty', sa.Integer(), nullable=True))
    op.add_column('service', sa.Column('qty_error', sa.String(length=200), nullable=True))
    op.add_column('service', sa.Column('selected', sa.Boolean(), nullable=True))
    op.add_column('service', sa.Column('modal_selected_KO', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'modal_selected_KO')
    op.drop_column('service', 'selected')
    op.drop_column('service', 'qty_error')
    op.drop_column('service', 'qty')
    op.drop_table('service_rols')
    # ### end Alembic commands ###
