"""empty message

Revision ID: 1de25bed54c5
Revises: 
Create Date: 2022-05-16 20:31:59.390179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de25bed54c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contraseña', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contraseña', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('semanas_embarazo', sa.Integer(), nullable=True),
    sa.Column('fecha_parto', sa.Date(), nullable=True),
    sa.Column('número_hijos', sa.Integer(), nullable=True),
    sa.Column('cesáreas', sa.Integer(), nullable=True),
    sa.Column('acompañante', sa.String(length=250), nullable=True),
    sa.Column('ubicación', sa.String(length=150), nullable=True),
    sa.Column('lugar_parto', sa.String(length=120), nullable=True),
    sa.Column('hospital_actual', sa.String(length=250), nullable=True),
    sa.Column('avatar', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuaria')
    op.drop_table('empresa')
    # ### end Alembic commands ###
