"""empty message

Revision ID: 27c1cec0a11f
Revises: 
Create Date: 2022-05-18 15:50:19.741659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c1cec0a11f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contraseña', sa.String(length=80), nullable=False),
    sa.Column('rol', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('datos__usuaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuaria_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('semanas_embarazo', sa.Integer(), nullable=True),
    sa.Column('fecha_aproximada_parto', sa.Date(), nullable=True),
    sa.Column('numero_hijos', sa.Integer(), nullable=True),
    sa.Column('numero_cesareas', sa.Integer(), nullable=True),
    sa.Column('acompanante', sa.String(length=250), nullable=True),
    sa.Column('ciudad', sa.String(length=150), nullable=True),
    sa.Column('lugar_parto', sa.String(length=120), nullable=True),
    sa.Column('hospital_actual', sa.String(length=250), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['usuaria_id'], ['usuarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datos__usuaria')
    op.drop_table('usuarias')
    # ### end Alembic commands ###
