"""empty message

Revision ID: 42321c07ca45
Revises: 7c67877dbbdc
Create Date: 2022-05-17 12:05:34.891829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42321c07ca45'
down_revision = '7c67877dbbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuaria', sa.Column('fecha_aproximada_parto', sa.Date(), nullable=True))
    op.alter_column('usuaria', 'avatar',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_column('usuaria', 'fecha_parto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuaria', sa.Column('fecha_parto', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('usuaria', 'avatar',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
    op.drop_column('usuaria', 'fecha_aproximada_parto')
    # ### end Alembic commands ###
