"""empty message

Revision ID: 63f2898a169d
Revises: 
Create Date: 2022-05-20 15:32:56.179590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f2898a169d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('rol', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user__data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('pregnancy_weeks', sa.Integer(), nullable=True),
    sa.Column('aproximate_birth_date', sa.Date(), nullable=True),
    sa.Column('children_number', sa.Integer(), nullable=True),
    sa.Column('caesarean_sections_number', sa.Integer(), nullable=True),
    sa.Column('companion', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('birth_place', sa.String(length=120), nullable=True),
    sa.Column('current_hospital', sa.String(length=250), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__data')
    op.drop_table('users')
    # ### end Alembic commands ###
