"""empty message

Revision ID: 72c7fd7d6a5f
Revises: cbc9cb539faa
Create Date: 2022-06-16 14:29:03.204612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c7fd7d6a5f'
down_revision = 'cbc9cb539faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('service', 'description_includes',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=1500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'description_includes',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('service', 'description',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###
