"""empty message

Revision ID: 7e502fdabb80
Revises: 0f58bbdb06cb
Create Date: 2022-06-01 17:13:35.387290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e502fdabb80'
down_revision = '0f58bbdb06cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=5), nullable=True),
    sa.Column('question', sa.String(length=200), nullable=True),
    sa.Column('answer_id', sa.String(length=5), nullable=True),
    sa.Column('answer', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('user_faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=5), nullable=True),
    sa.Column('question', sa.String(length=200), nullable=True),
    sa.Column('answer_id', sa.String(length=5), nullable=True),
    sa.Column('answer', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id'),
    sa.UniqueConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_faq')
    op.drop_table('business_faq')
    # ### end Alembic commands ###
