"""empty message

Revision ID: 83b9431aac07
Revises: 42321c07ca45
Create Date: 2022-05-17 19:12:00.781852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b9431aac07'
down_revision = '42321c07ca45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contraseña', sa.String(length=80), nullable=False),
    sa.Column('rol', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('datos__usuaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuaria_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('semanas_embarazo', sa.Integer(), nullable=True),
    sa.Column('fecha_aproximada_parto', sa.Date(), nullable=True),
    sa.Column('número_hijos', sa.Integer(), nullable=True),
    sa.Column('número_cesáreas', sa.Integer(), nullable=True),
    sa.Column('acompañante', sa.String(length=250), nullable=True),
    sa.Column('ciudad', sa.String(length=150), nullable=True),
    sa.Column('lugar_parto', sa.String(length=120), nullable=True),
    sa.Column('hospital_actual', sa.String(length=250), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['usuaria_id'], ['usuarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('empresa')
    op.drop_table('usuaria')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuaria',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('contraseña', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('semanas_embarazo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('número_hijos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cesáreas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acompañante', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('ubicación', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('lugar_parto', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('hospital_actual', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('fecha_aproximada_parto', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usuaria_pkey'),
    sa.UniqueConstraint('email', name='usuaria_email_key')
    )
    op.create_table('empresa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('contraseña', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='empresa_pkey'),
    sa.UniqueConstraint('email', name='empresa_email_key'),
    sa.UniqueConstraint('nombre', name='empresa_nombre_key')
    )
    op.drop_table('datos__usuaria')
    op.drop_table('usuarias')
    # ### end Alembic commands ###
