"""empty message

Revision ID: cbc9cb539faa
Revises: 7570fc45d876
Create Date: 2022-06-14 14:28:39.659205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc9cb539faa'
down_revision = '7570fc45d876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('stripe_product_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'stripe_product_id')
    # ### end Alembic commands ###
