"""empty message

Revision ID: d652913b3701
Revises: 4378bf1ae4e4
Create Date: 2022-06-20 23:10:16.721921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd652913b3701'
down_revision = '4378bf1ae4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('service', sa.Integer(), nullable=True))
    op.drop_constraint('appointment_service_id_fkey', 'appointment', type_='foreignkey')
    op.create_foreign_key(None, 'appointment', 'service', ['service'], ['id'])
    op.drop_column('appointment', 'service_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.create_foreign_key('appointment_service_id_fkey', 'appointment', 'service', ['service_id'], ['id'])
    op.drop_column('appointment', 'service')
    # ### end Alembic commands ###
