"""empty message

Revision ID: e351a039239e
Revises: a264dc9f9f8c
Create Date: 2022-06-30 20:15:34.903617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e351a039239e'
down_revision = 'a264dc9f9f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birthplan_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('birthplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('birthplan_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birthplan', sa.Integer(), nullable=False),
    sa.Column('birthplan_video_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('subtitle', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['birthplan'], ['birthplan.id'], ),
    sa.ForeignKeyConstraint(['birthplan_video_id'], ['birthplan_video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('birthplan_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birthplan', sa.Integer(), nullable=False),
    sa.Column('birthplan_section_id', sa.Integer(), nullable=False),
    sa.Column('answer_type', sa.String(length=50), nullable=False),
    sa.Column('answer_text', sa.String(length=300), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('input_text', sa.String(length=300), nullable=True),
    sa.Column('multiselect', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['birthplan'], ['birthplan.id'], ),
    sa.ForeignKeyConstraint(['birthplan_section_id'], ['birthplan_section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('birthplan_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birthplan', sa.Integer(), nullable=False),
    sa.Column('birthplan_section_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(length=600), nullable=False),
    sa.ForeignKeyConstraint(['birthplan'], ['birthplan.id'], ),
    sa.ForeignKeyConstraint(['birthplan_section_id'], ['birthplan_section.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('birthplan_form', sa.Column('birthplan', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'birthplan_form', 'birthplan', ['birthplan'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'birthplan_form', type_='foreignkey')
    op.drop_column('birthplan_form', 'birthplan')
    op.drop_table('birthplan_comment')
    op.drop_table('birthplan_answer')
    op.drop_table('birthplan_section')
    op.drop_table('birthplan')
    op.drop_table('birthplan_video')
    # ### end Alembic commands ###
