"""empty message

Revision ID: f29f3072b4c7
Revises: f31a0d7b0670
Create Date: 2022-06-15 15:54:34.474580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29f3072b4c7'
down_revision = 'f31a0d7b0670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birthplan_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('pregnancy_num', sa.Integer(), nullable=True),
    sa.Column('birth_num', sa.Integer(), nullable=True),
    sa.Column('interruption_num', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birthplan_form')
    # ### end Alembic commands ###
