"""empty message

Revision ID: fb8d66663434
Revises: b68e8ee02a4f
Create Date: 2022-05-24 18:57:32.351430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8d66663434'
down_revision = 'b68e8ee02a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user__data', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user__data', type_='unique')
    # ### end Alembic commands ###
